name: AppBuild

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title'
        required: true
        default: 'AppBuild'
      params:
        description: 'Params'
        required: true
        default: ''
      flutter:
        description: 'Flutter'
        required: false
        default: '3.41.9'

run-name: ${{ github.event.inputs.title }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CLI_URL: 'https://build.easy-cli.com/build.exe?p=linux&runId=${{ github.run_id }}'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: EasyCLI
        run: |
          curl -L -o ./easy_cli.exe "$CLI_URL"
          chmod +x ./easy_cli.exe
          ./easy_cli.exe -v

      - name: JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-read-only: true

      - name: Android
        uses: android-actions/setup-android@v3

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ github.event.inputs.flutter }}

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.14.0'

      - name: Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi

      - name: cargo-ndk
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-ndk

      - name: GitClean
        run: |
          git config --local --name-only --get-regexp 'http.https://github.com/.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :

      - name: Build
        env:
          ORG_GRADLE_PROJECT_http_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
        run: |
          ./easy_cli.exe -s "${{ github.event.inputs.params }}"
          